### ISSUE TITLE
Support Object Graphs / Associations between Entities

### ISSUE THREAD

**Issue by ldegen** [ldegen/tbob#11]
THIS ISSUE DESCRIPTION IS WORK IN PROGRESS!!!!

Consider a sitation like this:

```coffee
@factory "Node", ->
  @attr "id", @number
  @atr "name", @string, ["id"], (id)->"Name of #{id}"

@factory "DetailedNode", ->
  @extend "Node"

  @attr "parent"
    .type @optional @ref "Node"
    .meta assoc: 
      instanceOf: "Node"
      peerProperty: "children"

  @attr "children"
    .type @list @ref "Node
    .meta assoc:
      instanceOf: "Node"
      peerProperty: "parent"
```

What I want is to be able to write scenarios like this:

```yaml
---

- DetailedNode:
  id: 0
    
- DetailedNode:
  id: 1
  parent:
    id: 0
    name: "parent of 1"

- DetailedNode:
  id: 2
  parent:
    id: 0
  
```
